### PR TITLE
Migration PB message should be action within TX

### PR DESCRIPTION
**Pull request by magnetised**

### CODE REVIEW

**Comment by alco** [comment]
Somewhat off-topic question: can code generation from the .proto file happen as part of a build step to avoid checking the generated code into Git and keeping it manually updated?

**Comment by define-null** [comment]
I would probably say we should, however we also need to keep an eye on 2 things:
- bump high-level version of the protocol accordingly when we introduce backwards non-compatible changes
- modify mapping for high-level messages that can be send on the wire as individual messages

Both of them require manual intervention.

**Comment by magnetised** [comment]
oops. totally forgot the code regeneration... sorting now

**Comment by define-null** [comment]
So PR basically introduces non-compatible change (message rename). If Electric has not been updated to use 1.1 version - it's probably fine. If it has been updated though - we need to update code there as well. 

AFAIK SatMigration messages are not generated in production at the moment, so we are not strictly forced to upgrade protocol version.

**Comment by define-null** [comment]
Electric is still on 1.0 version.

**Review by define-null — APPROVED** [review]

**Pull request merged**
